version: '3'

services:
  vsgan_tensorrt:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: styler00dollar/vsgan_tensorrt:latest
    volumes:
      - ./:/workspace/tensorrt
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
                - compute
                - video
